# Generated by Django 2.0.3 on 2019-04-22 16:27

from django.db import migrations, models
import django.db.models.deletion
import recognition.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddQuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AddStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_paper', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=recognition.models.upload_location2, width_field='width_field')),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('width_field', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('qb_qno', models.CharField(max_length=5)),
                ('qb_class', models.IntegerField()),
                ('qb_answers', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('qp_series', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('question_paper', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=recognition.models.upload_location, width_field='width_field')),
                ('qp_class', models.IntegerField()),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_rollno', models.IntegerField(null=True)),
                ('s_name', models.CharField(max_length=128, null=True)),
                ('s_class', models.IntegerField(null=True)),
                ('s_school_name', models.CharField(max_length=128, null=True)),
                ('s_marks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=128, null=True)),
                ('t_email', models.EmailField(max_length=254, null=True)),
                ('t_password', models.CharField(max_length=30, null=True)),
                ('t_school_name', models.CharField(max_length=128, null=True)),
                ('security_question', models.CharField(max_length=128, null=True)),
                ('security_answer', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='questionbank',
            name='qb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognition.QuestionPaper'),
        ),
        migrations.AddField(
            model_name='addstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognition.Student'),
        ),
        migrations.AddField(
            model_name='addstudent',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognition.Teacher'),
        ),
        migrations.AddField(
            model_name='addquestionbank',
            name='questionpaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognition.QuestionPaper'),
        ),
        migrations.AddField(
            model_name='addquestionbank',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognition.Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='questionbank',
            unique_together={('qb_qno', 'qb', 'qb_class')},
        ),
        migrations.AlterUniqueTogether(
            name='addstudent',
            unique_together={('teacher', 'student')},
        ),
    ]
